export const IPC = {
  ListSessions: 'sessions:list',
  CreateSession: 'sessions:create',
  DeleteSession: 'sessions:delete',
  ListRepos: 'repos:list',
  GetSettings: 'settings:get',
  UpdateSettings: 'settings:update',
  PickDirectory: 'dialog:pickDirectory',
  RevealInFinder: 'shell:revealInFinder',
  OpenInITerm: 'shell:openInITerm',
  PtyStart: 'pty:start',
  PtyWrite: 'pty:write',
  PtyResize: 'pty:resize',
  PtyKill: 'pty:kill',
  PtyData: 'pty:data',
  PtyExit: 'pty:exit',
  PtyBacklog: 'pty:backlog',
  PtyActivity: 'pty:activity',
  PtyMarkIdle: 'pty:markIdle',
  SessionsSetWaitingOnReview: 'sessions:setWaitingOnReview',
  ReadAgentInstructions: 'agentInstructions:read',
  WriteAgentInstructions: 'agentInstructions:write',
  GetAgentSpend: 'agentSpend:get',
  DiaryList: 'diary:list',
  DiaryAdd: 'diary:add',
  DiaryToggleDone: 'diary:toggleDone',
  DiaryRemove: 'diary:remove',
  DiaryClearDoneBefore: 'diary:clearDoneBefore',
  GitStatus: 'git:status',
  GitDiff: 'git:diff',
  OpenInVSCode: 'shell:openInVSCode',
  AgentsDetect: 'agents:detect',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
